FROM tomcat


RUN mkdir /usr/local/tomcat/webapps/ROOT
RUN mkdir /usr/local/tomcat/webapps/appv
COPY index.html /usr/local/tomcat/webapps/ROOT/
COPY volumen.html /usr/local/tomcat/webapps/appv/index.html
