apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
    strategy:
      type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0.28
          env:
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysqldeploy
                key: my_sql_username
          - name: MYSQL_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: mysqldeploy
                key: my_sql_password
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysqldeploy
                key: my_database
          ports:
          - containerPort: 3306
            name: mysql