apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql_jmabellan
        image: MY_IMAGE
        valueFrom:
          configMapKeyRef:
            name: mysqlDeploy
            key: my_image
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
      env:
      - name: MYSQL_USER
        valueFrom:
          configMapKeyRef:
            name: mysqlDeploy
            key: my_sql_username
      - name: MYSQL_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: mysqlDeploy
            key: my_sql_password