---
- hosts: all
  become: yes
  become_method: su
  tasks:
  - name: Install packages
    apt:
      pkg: 
        - nginx
      state: present
      update_cache: true
  - name: Show versions
    ansible.builtin.command:
      cmd: "nginx -v"
    register: version_info
  - name: Version Info
    debug:
      msg: "Version Info: {{ version_info }}"
    when: version_info is changed
  - name: Copy index
    ansible.builtin.template:
      src: /home/bootuser/Documentos/ansible/task_11/assets/index.html
      dest: /var/www/html/index.html
  - name: Start nginx service
    ansible.builtin.service:
      name: nginx
      state: started
...   
