---
# tasks file for open-jdk
#Update and Upgrade repos
- name: Update and Upgrade
  apt: update_cache=yes upgrade=yes

- name: install openjdk V11
  apt:
    name: "{{ java_openjdk_v11 }}"
    update_cache: true
    state: present
    #cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"

- name: install openjdk V16
  apt:
    name: "{{ java_openjdk_v16 }}"
    update_cache: true
    state: present
    #cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
...



